<%@ Page Title="" Language="C#" MasterPageFile="~/Cursos/MPCursos.master" AutoEventWireup="true" CodeBehind="AdministrarCursos.aspx.cs" Inherits="Sistema_de_etiquetas.Cursos.AdministrarCursos" %>
<asp:Content ID="Content1" runat="server" contentplaceholderid="contenidoPrincipal">
    <h1>Administrar Cursos</h1>
    <p>
        <div runat="server" style="overflow-x:auto;width:556px; height:auto">
        <asp:GridView ID="grdAdministrarCursos" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowEditing="grdAdministrarCursos_RowEditing" OnRowCancelingEdit="grdAdministrarCursos_RowCancelingEdit" OnRowUpdating="grdAdministrarCursos_RowUpdating" OnRowDeleting="grdAdministrarCursos_RowDeleting">
        </asp:GridView>
            </div>
    </p>
</asp:Content>

